"""Change participants to JSON

Revision ID: aedd3eee176a
Revises: f3374ffba7c8
Create Date: 2025-03-28 11:25:01.170644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aedd3eee176a'
down_revision: Union[str, None] = 'f3374ffba7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    'rooms',
    'participants',
    type_=sa.JSON(),
    postgresql_using="participants::json"
)
    ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'participants',
               existing_type=sa.JSON(),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    ### end Alembic commands ###
